export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 15 ",
      imgSrc: 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71nvkHnPpZL._SX679_.jpg',
      // amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 15 (256 GB) - Green',
      price: '84900',
    },
    {
      id: 5,
      category: 'laptops',
      title: "HP Laptop 15s, AMD Ryzen 3 Laptop",
      imgSrc: 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71uIAPYktgL._SX679_.jpg',
      // amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'HP Laptop 15s, AMD Ryzen 3 5300U, 15.6-inch (39.6 cm), FHD',
      price: '33990',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Lenovo Tab M10 FHD Plus",
      imgSrc: 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/41TsQphTpGL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Lenovo Tab M10 FHD Plus(3rd Gen)| 10.61 Inch, 2K Display| 6 GB RAM, 128 GB ROM ',
      price: '15999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "HP Laptop 15s, AMD Ryzen 3 ",
      imgSrc: 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/41A-fFCcFyL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'HP Laptop 15s, AMD Ryzen 3 5300U, 15.6-inch ',
      price: '33990',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet',
      price: '49999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple 2022 MacBook",
      imgSrc: 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/41CvNGqdI3L._SY445_SX342_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple 2022 MacBook Air Laptop with M2 chip: 34.46 cm ',
      price: '114900',
    },


  ]